### ISSUE TITLE
Bootstrapping error when starting a cluster using examples/stargate-cass311.yml

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/docker-images#36]
I started a cluster using the following command in the examples directly:

`examples % docker-compose -f stargate-cass311.yml up -d
`

after giving the cluster a minute or two to start up, I see one of the C* nodes is down, in this case backend-3:

```
examples % docker-compose -f stargate-cass311.yml ps
  Name                 Command               State                              Ports
---------------------------------------------------------------------------------------------------------------
backend-1   docker-entrypoint.sh cassa ...   Up       7000/tcp, 7001/tcp, 7199/tcp, 0.0.0.0:9044->9042/tcp,
                                                      9160/tcp
backend-2   docker-entrypoint.sh cassa ...   Up       7000/tcp, 7001/tcp, 7199/tcp, 9042/tcp, 9160/tcp
backend-3   docker-entrypoint.sh cassa ...   Exit 3
stargate    ./starctl                        Up       0.0.0.0:8080->8080/tcp, 0.0.0.0:8081->8081/tcp,
                                                      0.0.0.0:8082->8082/tcp, 0.0.0.0:8084->8084/tcp,
                                                      0.0.0.0:9045->9042/tcp
```

Examining the logs for backend-3, I see the following:

```
backend-3    | INFO  [main] 2021-02-08 22:34:22,967 StorageService.java:1484 - JOINING: calculation complete, ready to bootstrap
backend-3    | Exception (java.lang.UnsupportedOperationException) encountered during startup: Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while cassandra.consistent.rangemovement is true. Nodes detected, bootstrapping: /172.18.0.3; leaving: ; moving: ;
backend-3    | java.lang.UnsupportedOperationException: Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while cassandra.consistent.rangemovement is true. Nodes detected, bootstrapping: /172.18.0.3; leaving: ; moving: ;
backend-3    | 	at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:969)
backend-3    | 	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:724)
backend-3    | 	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:658)
backend-3    | 	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:386)
backend-3    | 	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:628)
backend-3    | 	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:768)
backend-3    | ERROR [main] 2021-02-08 22:34:22,989 CassandraDaemon.java:785 - Exception encountered during startup
backend-3    | java.lang.UnsupportedOperationException: Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while cassandra.consistent.rangemovement is true. Nodes detected, bootstrapping: /172.18.0.3; leaving: ; moving: ;
backend-3    | 	at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:969) ~[apache-cassandra-3.11.8.jar:3.11.8]
backend-3    | 	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:724) ~[apache-cassandra-3.11.8.jar:3.11.8]
backend-3    | 	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:658) ~[apache-cassandra-3.11.8.jar:3.11.8]
backend-3    | 	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:386) [apache-cassandra-3.11.8.jar:3.11.8]
backend-3    | 	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:628) [apache-cassandra-3.11.8.jar:3.11.8]
backend-3    | 	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:768) [apache-cassandra-3.11.8.jar:3.11.8]
backend-3    | INFO  [StorageServiceShutdownHook] 2021-02-08 22:34:22,995 HintsService.java:209 - Paused hints dispatch
backend-3    | WARN  [StorageServiceShutdownHook] 2021-02-08 22:34:22,998 Gossiper.java:1669 - No local state, state is in silent shutdown, or node hasn't joined, not announcing shutdown
backend-3    | INFO  [StorageServiceShutdownHook] 2021-02-08 22:34:22,998 MessagingService.java:985 - Waiting for messaging service to quiesce
backend-3    | INFO  [ACCEPT-/172.18.0.5] 2021-02-08 22:34:22,999 MessagingService.java:1346 - MessagingService has terminated the accept() thread
backend-3    | INFO  [StorageServiceShutdownHook] 2021-02-08 22:34:23,059 HintsService.java:209 - Paused hints dispatch
backend-3 exited with code 3
```

**Comment by polandll** [comment]
Yes, I've definitely seen this happen.
