### ISSUE TITLE
Stargate 1.0.28 image for Cassandra 4.0 is broken

### ISSUE THREAD

**Issue by adejanovski** [stargate/docker-images#69]
We have a PR open to upgrade Stargate to 1.0.28 in K8ssandra but CI fails with the following error in our 4.0 integration tests (3.11 works fine):

```
Running java -server -XX:+CrashOnOutOfMemoryError -Xms300M -Xmx300M -Dstargate.libdir=./stargate-lib -Djava.awt.headless=true -jar ./stargate-lib/stargate-starter-1.0.28.jar --cluster-name k8ssandra --cluster-version 4.0 --cluster-seed k8ssandra-seed-service.k8ssandra2021062912511207.svc.cluster.local --listen 10.244.2.3 --dc dc1 --rack default --enable-auth
JAR DIR: ./stargate-lib
Unexpected error: No persistence backend found for cassandra 4.0
java.lang.IllegalArgumentException: No persistence backend found for cassandra 4.0
	at io.stargate.starter.Starter.pickBundles(Starter.java:510)
	at io.stargate.starter.Starter.start(Starter.java:399)
	at io.stargate.starter.Starter.cli(Starter.java:619)
	at io.stargate.starter.Starter.main(Starter.java:660)
```

According to @dougwettlaufer, it looks like Docker picked up the 3.11 layer for the 4.0 image: 

```
Executing ./cassandra-4.0/build.sh
951
Building stargateio/stargate-4_0
952
#1 [internal] load build definition from Dockerfile
953
#1 sha256:2bee95500cc0755835c17bb41a24d070d4ee880ceea538f061556b9f0f63a3fd
954
#1 transferring dockerfile: 32B done
955
#1 DONE 0.0s
956
957
#2 [internal] load .dockerignore
958
#2 sha256:ff1fccadef2060b37272e1f041da27ad20410656e35a3d2886d87f39512c4885
959
#2 transferring context: 2B done
960
#2 DONE 0.0s
961
962
#4 [linux/arm64 internal] load metadata for docker.io/library/openjdk:8u292-slim
963
#4 sha256:f360b442d65b23333e59d6908929faf42652e60186d6fada7f74ce8adb666b8a
964
#4 ...
965
966
#3 [linux/amd64 internal] load metadata for docker.io/library/openjdk:8u292-slim
967
#3 sha256:41472b54efa05e0f4be8844174a50e868bf802b00729261b349f88a41d562e5e
968
#3 DONE 0.2s
969
970
#4 [linux/arm64 internal] load metadata for docker.io/library/openjdk:8u292-slim
971
#4 sha256:f360b442d65b23333e59d6908929faf42652e60186d6fada7f74ce8adb666b8a
972
#4 DONE 0.2s
973
974
#5 [linux/arm64 1/4] FROM docker.io/library/openjdk:8u292-slim@sha256:04807e036d36ec583620468b1483fc8b4ea29868a859b0158ef1987f49f8af1c
975
#5 sha256:10cd1fa40749b52736f4a55c71edd84d43c50fb45747b6e988ae5d76c9601c6e
976
#5 resolve docker.io/library/openjdk:8u292-slim@sha256:04807e036d36ec583620468b1483fc8b4ea29868a859b0158ef1987f49f8af1c done
977
#5 DONE 0.0s
978
979
#7 [linux/arm64 3/4] RUN curl -L https://github.com/stargate/stargate/releases/download/v1.0.28/stargate-jars.zip > stargate-jars.zip     && unzip stargate-jars -x "*/persistence-*"     && unzip stargate-jars "*/persistence-api*"     && unzip stargate-jars "*/persistence-cassandra-3.11*"     && rm stargate-jars.zip
```

**Comment by ivansenic** [comment]
Problem was the build, see below in the logs how the build for `4_0` is taking 3.11 artifacts.. Kill if me if I know why, I checked everywhere..

**Comment by tatu-at-datastax** [comment]
This is an ancient version so as long as newer images are ok I don't think there's point in keeping this open; closing.
